name: Build and deploy latest changes & releases

on:
  push:
    branches: 
      - 'main'
      - 'RSDK-6991'
    paths-ignore:
      - '*.md'
  release:
    types: [published]

jobs:
  appimage:
    name: Build/Test/Upload latest
    runs-on: buildjet-2vcpu-ubuntu-2204-arm

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set version env var
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            apt-get update && apt-get install -y jq
            LATEST_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
            echo "VERSION=$LATEST_RELEASE-${{ github.ref_name }}.${{ github.run_number }}" >> $GITHUB_ENV
          fi

      - name: Build appimage release
        run: make appimage-aarch64

      - name: Authorize GCP upload
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Upload appimage to GCP
        uses: google-github-actions/upload-cloud-storage@v0.10.4
        with:
          headers: "cache-control: no-cache"
          path: 'viam-camera-oak-latest-aarch64.AppImage'
          destination: 'packages.viam.com/apps/oak/linux'
          parent: false
          gzip: false

      - name: Upload to registry (linux/arm64 appimage)
        uses: viamrobotics/upload-module@main
        if: github.event_name == 'push'
        with:
          meta-path: meta.json
          module-path: 'module.tar.gz'
          platform: linux/arm64
          version: ${{ env.VERSION }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}

      # Make sure to run this after appimage stuff is finished
      # `make clean` is called and will delete previous artifacts e.g. appimage & the previous tar ball
      - name: Build non-appimage release
        run: make non-appimage

      - name: Upload to registry (darwin/arm64 non-appimage)
        uses: viamrobotics/upload-module@main
        with:
          meta-path: meta.json
          module-path: 'module.tar.gz'
          platform: darwin/arm64
          version: ${{ env.VERSION }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}

      - name: Upload to registry (darwin/amd64 non-appimage)
        uses: viamrobotics/upload-module@main
        with:
          meta-path: meta.json
          module-path: 'module.tar.gz'
          platform: darwin/amd64
          version: ${{ env.VERSION }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}
