name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make setup

    - name: Run lint
      run: |
        make lint-check
        if [ $? -ne 0 ]; then
          echo "Black formatting check failed. Please fix the issues."
          exit 1
        fi

    - name: Run unit tests
      run: make test
