name: Publish module to registry (arm64 builds only)

on:
  push:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: viamrobotics/build-action@v1
      with:
        # version: ${{ github.ref_name }}
        version: 0.2.1-rc-4
        ref: ${{ github.sha }}
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}
