name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Run unit tests"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install -r requirements-dev.txt

    - name: Run lint
      run: |
        make lint-check

    - name: Run unit tests
      run: make test
