name: Upload to GCP

on:
  push:
    branches: 
      - 'main'
    paths-ignore:
      - '*.md'

jobs:
  upload-gcp:
    name: Build and upload AppImage to GCP
    runs-on: buildjet-2vcpu-ubuntu-2204-arm

    steps:
      - uses: actions/checkout@v3

      - name: Build appimage release
        run: make appimage-aarch64

      - name: Authorize GCP upload
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Upload appimage to GCP
        uses: google-github-actions/upload-cloud-storage@v0.10.4
        with:
          headers: "cache-control: no-cache"
          path: 'viam-camera-oak-latest-aarch64.AppImage'
          destination: 'packages.viam.com/apps/oak/linux'
          parent: false
          gzip: false
